name: flutter_web_cv_portfolio
description: "Wild Ea$t"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.8
  auto_route: 10.2.2
  intl: 0.20.2
  flutter_bloc: 9.1.1
  equatable: 2.0.7
  provider: 6.1.5
  nested: 1.0.0
  ui_kit:
    path: packages/ui_kit
  utils:
    path: packages/utils
  web: 1.1.1
  card_swiper: 3.0.1
  native_web_scroll: 1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  lints: 6.0.0
  auto_route_generator: 10.2.6
  build_runner: 2.10.4

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Inter
      fonts:
        - asset: packages/ui_kit/assets/fonts/Inter-VariableFont_opsz,wght.ttf
    - family: Mabry Pro
      fonts:
        - asset: packages/ui_kit/assets/fonts/MabryPro-Regular.ttf
    - family: Onder
      fonts:
        - asset: packages/ui_kit/assets/fonts/Onder-Regular.ttf
      