name: ui_kit
description: "UiKit package for Realt One project"
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  # Стандартный пакет флаттер-а.
  flutter:
    sdk: flutter
  # Пакет навигации.
  auto_route: 10.2.2
  utils:
    path: ../utils
  # Пакет для отображения SVG изображений.
  flutter_svg: 2.2.0
  # Пакет для отображения изображений.
  extended_image: 10.0.1
  # Плагин для работы с путями
  path: 1.9.1
  # Пакет предоставляет простой способ добавить эффект мерцания в проект Flutter
  shimmer: 3.0.0
  # Пакет для работы с Swiper
  card_swiper: 3.0.1


dev_dependencies:
  # Пакет для поддержки кодогенерации.
  build_runner: 2.10.4
  # Пакет для кодогенерации для ассетов - цвета, шрифты, иконки, изображения.
  flutter_gen_runner: 5.12.0
  # Пакет с набором правил линтера.
  flutter_lints: 6.0.0


flutter_gen:
  output: lib/assets
  assets:
    outputs:
      package_parameter_enabled: true
  colors:
    enabled: true
    outputs:
      class_name: UiKitColor
    inputs:
      - assets/color/colors.xml
  fonts:
    enabled: true


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/project_icons/
    - assets/images/store_badges/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
    - family: Mabry Pro
      fonts:
        - asset: assets/fonts/MabryPro-Regular.ttf
    - family: Onder
      fonts:
        - asset: assets/fonts/Onder-Regular.ttf

